### ISSUE TITLE
Package filecontents Warning: This package is obsolete.

### ISSUE THREAD

**Issue by kiryph** [Ossifragus/runcode#11]
https://ctan.org/pkg/filecontents

> As of September 2019 the author tells us: “This package is no longer necessary due to its functionality having moved into recent LATEX kernels. It’s probably better not to move the package to obsolete because users may need it to rebuild old documents. Version 1.5 provides full functionality when run with an older kernel but issues a warning message and disables itself when run with a newer kernel.”

Is it possible to not load the package filecontents to remove this warning? I always appreciate less warnings (in the best case none).

**Comment by Ossifragus** [comment]
Done with 405513c9db7cdecedc57eddc2afcd73d94d88e4a.
