### ISSUE TITLE
Use \inln inside tikzpicture

### ISSUE THREAD

**Issue by kiryph** [Ossifragus/runcode#6]
I want to use the [GAP system](https://www.gap-system.org/) to produce a [TikZ path](https://github.com/pgf-tikz/pgf) which I want to include inside a tikzpicture environment in a  LaTeX document:

```tex
\documentclass{article}

\usepackage[nominted]{runcode}
\usepackage{tikz}

\begin{document}
\begin{tikzpicture}
\inln{gap -b --nointeract}{PrintTo("*stdout*", "\\draw (0,0) -- (1,0);");}
\end{tikzpicture}
\end{document}
```

However, `runcode` changes the output string in `generated/demo_inln1.txt` to
```
PrintTo("*stdout*", "\protect \@normalcr \protect \@normalcr draw (0,0) -- (0,0);");
```

My actual issue is when using a GAP function which returns a TikZ string. This already reduces many problems.

Consider this simple GAP function, e.g. defined in the user gaprc file (macOS path `~/Library/Preferences/GAP/gaprc`):

```gap
TikZStringTest := function()
  SetPrintFormattingStatus("*stdout*", false); # do not introduce line breaks with continuation characters which are not understood by tex/tikz
  Print("\\draw (0,0) -- (1,0) -- (1,1) -- cycle);");
end;
```

```tex
\documentclass{article}

\usepackage[nominted]{runcode}
\usepackage{tikz}

\begin{document}
\begin{tikzpicture}
\inln{gap -b --nointeract}{TikZStringTest();}
\end{tikzpicture}
\end{document}
```

The generated file `generated/demo_inln1.txt` looks good:

```
TikZStringTest();
```
The first mentioned issue does not appear for strings like `TikZStringTest();`
The generated tex file is
```
^M\draw (0,0) -- (1,0) -- (1,1) -- cycle;
```

However, one warning remains:

```
Missing character: There is no - in font nullfont!
```

I am struggling to find the actual reason for this warning. I doubt that the leading `^M` is responsible for the warning.

### Note 
Following works without warnings
```tex
\runExtCode{gap -b --nointeract}{mygapcode.gap}{outname}
\begin{tikzpicture}[x=1.5cm,y=1.5cm]
\includeOutput{outname}[tex]
\end{tikzpicture}

**Comment by haimbar** [comment]
Thanks for the bug report! Although there is a workaround, as you pointed out, this was a more general bug which would have affected any code which contains characters (like backslash) which are designated as "special" by latex.  These characters are escaped by latex when they are passed to macros as arguments, which, in the case of \inln, alters the correct syntax and causes execution errors.
We fixed it by wrapping the code which is passed to \inln with \detokenize. It ensures that the code is passed as-is to R/Julia/MatLab/Python (or gap.)

**Comment by kiryph** [comment]
Thanks for all the recent updates.

I have dowloaded the most recent `runcode.sty` v2.1 to the MWE directory
```sh
❯ ls -1 demo.tex mygapcode.gap runcode.sty
demo.tex
mygapcode.gap
runcode.sty

❯ head -n 7 runcode.sty
%
%  Haim Bar      haim.bar@uconn.edu
%  HaiYing Wang  haiying.wang@uconn.edu
%
%  This package is based on an ongoing work by Haim Bar and HaiYing Wang, and comments and questions are welcome!

\ProvidesPackage{runcode}[2023/06/30 runcode v2.1]
```

```tex
% file: demo.tex
\documentclass{article}

\usepackage[nominted]{runcode}
\usepackage{tikz}

\begin{document}
  
\runExtCode{gap -b --nointeract}{mygapcode.gap}{outname}
\begin{tikzpicture}[x=1.5cm,y=1.5cm]
  \includeOutput{outname}[tex]
\end{tikzpicture}

\begin{tikzpicture}
\inln{gap -b --nointeract}{TikZStringTest();}
\end{tikzpicture}

\end{document}
```
```gap
# file: mygapcode.gap
SetPrintFormattingStatus("*stdout*", false);
Print("\\draw (0,0) -- (1,0) -- (1,1) -- cycle);");
```

However, I still get nullfont warnings in tikz environments also for `\inln{}`:
```
$ pdflatex --shell-escape demo.tex > /dev/null && grep "runcode\|Missing" demo.log
) (./runcode.sty
Package: runcode 2023/06/30 runcode v2.1
Missing character: There is no - in font nullfont!
Missing character: There is no - in font nullfont!
```

I assume `\includeOutput` inside tikz environments is also affected, in contrast what my note of the first posting says.
