### ISSUE TITLE
Feature request: Add cache option to \inln

### ISSUE THREAD

**Issue by kiryph** [Ossifragus/runcode#7]
When using many `\inln` commands, compilation of a document becomes slow. However, many `\inlin` commands do not change anymore. Therefore, it would be nice to have a `cache` option similar to `\runExtCode`.

**Comment by haimbar** [comment]
Great suggestion. We added the option to the \inln function. We added a new variable called inlnrun which is set to true by default. If changed to false, then all \inln instances will use cache files. If cache files are not available, the \inln code will run.
To use it locally, invoke \inln with 4 arguments and simply append .cache at the end (so it will be either vbox.cache or just .cache, for placing the output inline.
